### ISSUE TITLE
Fix it please for version 2023.1

### ISSUE THREAD

**Issue by sl3w** [saundefined/bitrix-idea#2]
I updated phpStorm, and after that plugin don't work :( Fix it please

**Comment by saundefined** [comment]
Hi,

The update has been in moderation at JetBrains since March 16,

while you can install the update manually:
https://github.com/saundefined/bitrix-idea/releases/tag/v2023.1.0

<img width="400" alt="image" src="https://user-images.githubusercontent.com/4685504/230612992-c9fcfd01-9726-4b5c-ae4b-c5f4aba1146f.png">

**Comment by sl3w** [comment]
Thanks!

**Comment by epicuristic** [comment]
@saundefined plugin shows as freemium, but I did not find any info about pricing plans.
